import { User, RideGroup, Message } from './types';

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Karim Ahmed', phone: '+966501234567', email: 'karim@hayghoride.com', photo: 'https://picsum.photos/seed/karim/100/100', preferredRideType: 'Motorcycle', emergencyContact: { name: 'Aisha Ahmed', phone: '+966509876543' } },
  { id: 'u2', name: 'John Smith', phone: '+1-555-123-4567', email: 'john@hayghoride.com', photo: 'https://picsum.photos/seed/john/100/100', preferredRideType: 'ATV', emergencyContact: { name: 'Jane Smith', phone: '+1-555-987-6543' } },
  { id: 'u3', name: 'Fatima Al-Fassi', phone: '+966551122334', email: 'fatima@hayghoride.com', photo: 'https://picsum.photos/seed/fatima/100/100', preferredRideType: 'Side-by-Side' },
];

export const MOCK_RIDES: RideGroup[] = [
  {
    id: 'r1',
    name: 'Jeddah Coastal Road Cruise',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'A scenic coastal motorcycle ride along the Jeddah corniche. Mostly flat, perfect for all skill levels. We will watch the sunset there.',
    destination: {
      name: 'Jeddah Corniche Circuit',
      mapsLink: 'https://www.google.com/maps/search/?api=1&query=Jeddah+Corniche+Circuit',
    },
    createdBy: 'u1',
    rideStatus: 'Upcoming',
    participants: ['u1', 'u3'],
    reminder: '24h',
  },
  {
    id: 'r2',
    name: 'Red Sands ATV Adventure',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'An exciting ATV ride through the Red Sands near Riyadh. For experienced riders. The dune views are worth it!',
    destination: {
      name: 'Red Sand Dunes, Riyadh',
      mapsLink: 'https://www.google.com/maps/search/?api=1&query=Red+Sand+Dunes+Riyadh',
    },
    createdBy: 'u2',
    rideStatus: 'Upcoming',
    participants: ['u2'],
    reminder: '1h',
  },
  {
    id: 'r3',
    name: 'Wadi Al-Disah Exploration',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    description: 'A relaxing side-by-side ride through Wadi Al-Disah last weekend. Great for a casual spin.',
    destination: {
      name: 'Wadi Al Disah, Tabuk Province',
      mapsLink: 'https://www.google.com/maps/search/?api=1&query=Wadi+Al+Disah',
    },
    createdBy: 'u3',
    rideStatus: 'Completed',
    participants: ['u3', 'u1', 'u2'],
    reminder: 'none',
    ratings: [{ userId: 'u3', rating: 5 }, { userId: 'u1', rating: 4 }, { userId: 'u2', rating: 5 }],
    distance: 45, // km
    duration: '2h 30m'
  },
];

export const MOCK_MESSAGES: Message[] = [
    { id: 'm1', rideId: 'r1', senderId: 'u1', message: 'Hey everyone, looking forward to the ride on Friday! Let\'s meet at 4 PM.', timestamp: Date.now() - 60000 * 5 },
    { id: 'm2', rideId: 'r1', senderId: 'u3', message: 'Sounds good! I\'ll be there. Is the route windy?', timestamp: Date.now() - 60000 * 4 },
    { id: 'm3', rideId: 'r1', senderId: 'u1', message: 'It can be, make sure to bring a light jacket!', timestamp: Date.now() - 60000 * 3 },
];

export const translations = {
    en: {
        appName: "HAYGHORIDE",
        navHome: "Discover",
        navMyRides: "My Rides",
        navCreateRide: "Create Ride",
        navChat: "Chat",
        navProfile: "Profile",
        welcome: "Welcome to HAYGHORIDE",
        welcomeSub: "Your next adventure is just a tap away. Join or create group rides with fellow enthusiasts.",
        findRides: "Find Rides",
        upcomingRides: "Upcoming Rides",
        pastRides: "Past Rides",
        noUpcomingRides: "No upcoming rides. Why not create one?",
        noPastRides: "No past rides yet.",
        createRideTitle: "Create a New Ride",
        rideName: "Ride Name",
        rideNamePlaceholder: "e.g., Friday Evening Cruise",
        destination: "Destination",
        destinationPlaceholder: "e.g., A cool cafe in Al-Balad, Jeddah",
        rideDate: "Date",
        rideTime: "Time",
        description: "Description",
        descriptionPlaceholder: "Tell us about the ride...",
        findDestination: "Find Destination",
        finding: "Finding...",
        createRideButton: "Create Ride",
        joinRide: "Join Ride",
        leaveRide: "Leave Ride",
        participants: "Participants",
        viewOnMap: "View on Map",
        chat: "Chat",
        sendMessage: "Send Message",
        messagePlaceholder: "Type your message...",
        rideDetails: "Ride Details",
        createdBy: "Created by",
        status: "Status",
        myProfile: "My Profile",
        name: "Name",
        phone: "Phone",
        email: "Email",
        preferredVehicle: "Preferred Vehicle",
        editRide: "Edit Ride",
        endRide: "End Ride",
        cancelRide: "Cancel Ride",
        remove: "Remove",
        add: "Add",
        addParticipant: "Add Participant",
        loginTitle: "Select Your Profile",
        loginAs: "Login as",
        logout: "Logout",
        discoverRides: "Discover Rides",
        discoverSub: "Find new adventures and join fellow riders.",
        noDiscoverRides: "No new rides to join right now. Check back later!",
        reminder: "Reminder",
        reminderNone: "None",
        reminder1h: "1 hour before",
        reminder24h: "24 hours before",
        emergencyContact: "Emergency Contact",
        noEmergencyContact: "Not set",
        emergencyShare: "SOS: Share Location",
        emergencyMessage: "I need help! This is my current location:",
        startRide: "Start Ride",
        rideInProgress: "Ride in Progress",
        rateThisRide: "Rate this Ride",
        yourRating: "Your Rating",
        submitRating: "Submit",
        thankYouForRating: "Thank you for your feedback!",
        rideStats: "Ride Stats",
        distance: "Distance",
        duration: "Duration",
        avgRating: "Avg. Rating",
        outOf5: "out of 5",
        viewProfile: "View Profile",
    },
    ar: {
        appName: "هيّا عالرايد",
        navHome: "اكتشف",
        navMyRides: "رايداتي",
        navCreateRide: "أنشئ رايد",
        navChat: "الدردشة",
        navProfile: "ملفي",
        welcome: "أهلاً بك في هيّا عالرايد",
        welcomeSub: "مغامرتك القادمة على بعد نقرة واحدة. انضم أو أنشئ رايدات جماعية مع زملائك.",
        findRides: "ابحث عن رايدات",
        upcomingRides: "الرايدات القادمة",
        pastRides: "الرايدات السابقة",
        noUpcomingRides: "لا توجد رايدات قادمة. لم لا تنشئ واحدة؟",
        noPastRides: "لا توجد رايدات سابقة بعد.",
        createRideTitle: "أنشئ رايد جديد",
        rideName: "اسم الرايد",
        rideNamePlaceholder: "مثال: رايد مساء الجمعة",
        destination: "الوجهة",
        destinationPlaceholder: "مثال: مقهى جميل في البلد، جدة",
        rideDate: "التاريخ",
        rideTime: "الوقت",
        description: "الوصف",
        descriptionPlaceholder: "أخبرنا عن الرايد...",
        findDestination: "ابحث عن الوجهة",
        finding: "جاري البحث...",
        createRideButton: "أنشئ الرايد",
        joinRide: "انضم للرايد",
        leaveRide: "غادر الرايد",
        participants: "المشاركون",
        viewOnMap: "عرض على الخريطة",
        chat: "الدردشة",
        sendMessage: "إرسال",
        messagePlaceholder: "اكتب رسالتك...",
        rideDetails: "تفاصيل الرايد",
        createdBy: "أنشأها",
        status: "الحالة",
        myProfile: "ملفي الشخصي",
        name: "الاسم",
        phone: "الجوال",
        email: "البريد الإلكتروني",
        preferredVehicle: "المركبة المفضلة",
        editRide: "تعديل الرايد",
        endRide: "إنهاء الرايد",
        cancelRide: "إلغاء الرايد",
        remove: "إزالة",
        add: "إضافة",
        addParticipant: "إضافة مشارك",
        loginTitle: "اختر ملفك الشخصي",
        loginAs: "تسجيل الدخول كـ",
        logout: "تسجيل الخروج",
        discoverRides: "اكتشف الرايدات",
        discoverSub: "ابحث عن مغامرات جديدة وانضم إلى زملائك.",
        noDiscoverRides: "لا توجد رايدات جديدة للانضمام إليها الآن. تحقق مرة أخرى لاحقًا!",
        reminder: "تذكير",
        reminderNone: "بدون",
        reminder1h: "قبل ساعة",
        reminder24h: "قبل 24 ساعة",
        emergencyContact: "جهة اتصال للطوارئ",
        noEmergencyContact: "لم يتم التعيين",
        emergencyShare: "SOS: مشاركة الموقع",
        emergencyMessage: "أحتاج إلى مساعدة! هذا هو موقعي الحالي:",
        startRide: "ابدأ الرايد",
        rideInProgress: "الرايد قيد التقدم",
        rateThisRide: "قيّم هذا الرايد",
        yourRating: "تقييمك",
        submitRating: "إرسال",
        thankYouForRating: "شكرا لك على تقييمك!",
        rideStats: "إحصائيات الرايد",
        distance: "المسافة",
        duration: "المدة",
        avgRating: "متوسط التقييم",
        outOf5: "من 5",
        viewProfile: "عرض الملف الشخصي",
    }
};